### PR TITLE
Support Loading local model

### PR DESCRIPTION
**Pull request by sdbds**
1、Add load local model,use arg to set
2、Try to support MAC MPS

### CODE REVIEW

**Comment by sdbds** [comment]
I made windows version for auto install
https://github.com/sdbds/PhotoMaker-for-windows/tree/windows

**Comment by xhoxye** [comment]
QQ截图20240118084821

**Comment by EdwardOwusuAdjei** [comment]
@sdbds  it supports mac's mps now from  https://github.com/TencentARC/PhotoMaker/pull/17

**Comment by Paper99** [comment]
The compatibility difference between this PR and the existing code is too great. It seems to be more suitable for webui. I will list the version you gave in the README.

**Comment by sdbds** [comment]
> QQ截图20240118084821
> 
> QQ截图20240118090119

Seems diffusers version problem

**Comment by sdbds** [comment]
> @sdbds it supports mac's mps now from #17

i use all device include intel ipex

**Comment by sdbds** [comment]
> The compatibility difference between this PR and the existing code is too great. It seems to be more suitable for webui. I will list the version you gave in the README.

Thank you for replying.

**Comment by xhoxye** [comment]
diffusers==0.25.0
I uninstall and reinstall diffusers, same result, how to solve it

**Comment by sdbds** [comment]
> diffusers==0.25.0 I uninstall and reinstall diffusers, same result, how to solve it

did u install torch>2.0?

**Comment by sdbds** [comment]
> QQ截图20240118084821
> 
> QQ截图20240118090119

i remove it now,it should work in diffusers model

**Pull request closed without merging**
